name: C/C++ CI

on: [push, pull_request]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [g++, clang++]
    steps:
    - uses: actions/checkout@v1
    - name: dependencies
      run: sudo apt update && sudo apt install libboost-all-dev libmsgpack-dev ninja-build
    - name: configure
      env:
        CXX: ${{ matrix.compiler }}
      run: ./configure
    - name: build
      run: cmake --build build

  build-macos:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: dependencies
      run: brew update && brew install boost msgpack ninja
    - name: configure
      run: ./configure
    - name: build
      run: cmake --build build

  lint-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: dependencies
        run: pip3 install cpplint
      - name: cpplint
        run: cpplint --filter=-build/c++11 **/*.{cpp,h}